
CFLAGS = -g

all: pipe_lat pipe_thr pipe_bandwidth\
	unix_lat unix_thr unix_bandwidth\
	tcp_lat tcp_thr tcp_bandwidth\

clean:
	rm -f *~ core
	rm -f pipe_lat pipe_thr pipe_bandwidth
	rm -f unix_lat unix_thr unix_bandwidth
	rm -f tcp_lat tcp_thr tcp_bandwidth
	rm -f tcp_local_lat tcp_remote_lat 
	rm -f shm 
